[metadata]
creation_date = "2022/11/16"
maturity = "production"
updated_date = "2022/11/16"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"

[rule]
author = ["Elastic"]
description = """
This rule uses alert data to determine when a malware signature is triggered in multiple hosts. Analysts can use this
to prioritize triage and response, as this can potentially indicate a widespread malware infection.
"""
from = "now-24h"
interval = "1h"
index = [".alerts-*"]
language = "kuery"
license = "Elastic License v2"
name = "Potential Widespread Malware Infection"
risk_score = 73
rule_id = "a62a4300-0bb3-4301-9b64-d11411ff6fda"
severity = "high"
tags = ["Elastic", "Threat Detection", "Higher-Order Rules"]
timestamp_override = "event.ingested"
type = "threshold"

query = '''
event.code:"memory_signature" and signal.rule.name:*
'''

[rule.threshold]
field = ["rule.id"]
value = 1

[[rule.threshold.cardinality]]
field = "host.id"
value = 5
