[metadata]
creation_date = "2023/01/18"
integration = ["endpoint", "windows"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup"
min_stack_version = "8.3.0"
updated_date = "2023/01/18"

[rule]
author = ["Elastic"]
description = """
Identifies instances of common browsers (iexplore.exe, chrome and firefox.exe) with no process arguments and making
network connections. Adversaries could abuse this behavior to avoid suspicious processes making network connections 
and bypass host-based firewall restrictions.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "eql"
license = "Elastic License v2"
name = "Potential Command and Control via a Browser"
risk_score = 47
rule_id = "dd4a1971-39b0-4977-b593-03b62d072bb6"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion", "Command and Control"]
type = "eql"

query = '''
sequence by process.entity_id with maxspan=1m
 [process where event.type == "start" and 
  process.name : ("iexplore.exe", "chrome.exe", "firefox.exe") and process.args_count <=1 and 
  not startswith~(process.name, process.parent.name)]
 [network where event.action : ("lookup_requested", "Dns query*") and 
  process.name : ("iexplore.exe", "chrome.exe", "firefox.exe") and 
  not (dns.question.name : 
             ("*.microsoft.com", 
             "*.digicert.com", 
             "*.msocsp.com", 
             "*.msn.com",
             "*.windowsupdate.com", 
             "*.bing.com", 
             "*.identrust.com", 
             "*.sharepoint.com", 
             "*.office365.com", 
             "*.office.com", 
             "*.in-addr.arpa.", 
             "www.google-analytics.com", 
             "fonts.googleapis.com", 
             "update.googleapis.com", 
             "www.google.com", 
             "ocsp.*.com", 
             "ocsp.*.net", 
             "dl.dell.com") and not dns.question.name : "graph.microsoft.com")]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"


[rule.threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"

[[rule.threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
