[metadata]
creation_date = "2022/10/20"
integration = ["endpoint"]
maturity = "production"
min_stack_comments = "New fields added: required_fields, related_integrations, setup, process.Ext.effective_parent.executable"
min_stack_version = "8.4.0"
updated_date = "2023/02/06"

[rule]
author = ["Elastic"]
description = """
Identifies the creation of a process running as SYSTEM and impersonating a Windows core binary privileges. Adversaries
may create a new process with a different token to escalate privileges and bypass access controls.
"""
from = "now-9m"
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License v2"
name = "Process Created with an Elevated Token"
references = [
    "https://lengjibo.github.io/token/",
    "https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw",
]
risk_score = 73
rule_id = "02a23ee7-c8f8-4701-b99d-e9038ce313cb"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Privilege Escalation"]
timestamp_override = "event.ingested"
type = "eql"

query = '''
/* This rule is only compatible with Elastic Endpoint 8.4+ */

process where event.action == "start" and

 /* CreateProcessWithToken and effective parent is a privileged MS native binary used as a target for token theft */
 user.id : "S-1-5-18"  and

 /* Token Theft target process usually running as service are located in one of the following paths */
 process.Ext.effective_parent.executable :
                ("?:\\Windows\\*.exe",
                 "?:\\Program Files\\*.exe",
                 "?:\\Program Files (x86)\\*.exe",
                 "?:\\ProgramData\\*") and

 not (process.Ext.effective_parent.executable : "?:\\Windows\\System32\\Utilman.exe" and
      process.parent.executable : "?:\\Windows\\System32\\Utilman.exe" and process.parent.args : "/debug") and

 not process.executable : ("?:\\Windows\\System32\\WerFault.exe",
                           "?:\\Windows\\SysWOW64\\WerFault.exe",
                           "?:\\Windows\\System32\\WerFaultSecure.exe",
                           "?:\\Windows\\SysWOW64\\WerFaultSecure.exe",
                           "?:\\windows\\system32\\WerMgr.exe",
                           "?:\\Windows\\System32\\ROUTE.EXE",
                           "?:\\Windows\\System32\\inetsrv\\iissetup.exe",
                           "?:\\Windows\\SoftwareDistribution\\Download\\Install\\securityhealthsetup.exe", 
                           "?:\\Program Files (x86)\\Access\\Intelligent Form\\Win32Bin\\LaunchCreate.exe", 
                           "?:\\Windows\\Microsoft.NET\\Framework*\\Ngen.exe", 
                           "?:\\Windows\\SysWOW64\\BRRBTOOL.EXE", 
                           "?:\\Program Files\\Cisco\\AMP\\*\\cscm.exe", 
                           "?:\\Program Files (x86)\\CutePDF Writer\\CPWSave.exe", 
                           "?:\\Program Files (x86)\\CutePDF Writer\\CPWriter2.exe", 
                           "?:\\Windows\\system32\\powercfg.exe", 
                           "?:\\Windows\\System32\\SecEdit.exe", 
                           "?:\\Program Files\\Cisco\\AMP\\*\\cscm.exe", 
                           "?:\\Windows\\System32\\wevtutil.exe", 
                           "?:\\Program Files\\NDDigital\\nddPrint\\Releaser\\nddPrint.Releaser.ReleaserCap.exe")  and 
                           
 not (process.executable : "?:\\Windows\\System32\\spool\\drivers\\x64\\*.EXE" and 
      process.parent.executable : "?:\\Windows\\System32\\PrintIsolationHost.exe") and 

 not process.parent.executable : 
            ("?:\\Windows\\System32\\AtBroker.exe", 
             "?:\\Windows\\system32\\svchost.exe", 
             "?:\\Program Files (x86)\\*.exe", 
             "?:\\Program Files\\*.exe", 
             "?:\\Windows\\System32\\msiexec.exe", 
             "?:\\Windows\\System32\\DriverStore\\*", 
             "?:\\Windows\\System32\\wbem\\WmiPrvSE.exe", 
             "?:\\Windows\\WinSxS\\*\\TiWorker.exe") and


 not (process.code_signature.trusted == true and
      process.code_signature.subject_name : ("philandro Software GmbH", "Freedom Scientific Inc.", "TeamViewer Germany GmbH", "Projector.is, Inc.", 
                                             "TeamViewer GmbH", "Cisco WebEx LLC", "Dell Inc", "Cisco Systems, Inc.", "Lenovo")) and 
      
 not (process.executable : "?:\\Windows\\system32\\schtasks.exe" and process.args : "/Run" and 
      process.args : "Microsoft\\Configuration Manager\\Configuration Manager Health Evaluation") and 
 not (process.executable : "?:\\WINDOWS\\system32\\msiexec.exe" and process.args : "/x") and 
 not (process.name : "powershell.exe" and 
      process.command_line : "\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -Version 5.1 -s -NoLogo -NoProfile")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1134"
name = "Access Token Manipulation"
reference = "https://attack.mitre.org/techniques/T1134/"
[[rule.threat.technique.subtechnique]]
id = "T1134.002"
name = "Create Process with Token"
reference = "https://attack.mitre.org/techniques/T1134/002/"



[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

